---
version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: weekly
    commit-message:
      prefix: "HUSH-777 "
    groups:
      actions:
        patterns:
          - "*"
  - package-ecosystem: gomod
    directories:
      - "/"
      - "/**/*"
    schedule:
      interval: weekly
    commit-message:
      prefix: "HUSH-777 "
    groups:
      go-deps:
        patterns:
          - "*"
