package sendgrid_access_privilege

import (
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/schema"
	"github.com/hashicorp/terraform-plugin-sdk/v2/helper/validation"
)

const (
	idDesc          = "The unique identifier of the SendGrid access privilege"
	nameDesc        = "The name of the SendGrid access privilege"
	descriptionDesc = "The description of the SendGrid access privilege"
	scopesDesc      = "The list of SendGrid API scopes"
	typeDesc        = "The type of access privilege"
)

var validScopes = []string{
	"2fa_required",
	"access_settings.activity.read",
	"access_settings.whitelist.create",
	"access_settings.whitelist.delete",
	"access_settings.whitelist.read",
	"access_settings.whitelist.update",
	"alerts.create",
	"alerts.delete",
	"alerts.read",
	"alerts.update",
	"api_keys.create",
	"api_keys.delete",
	"api_keys.read",
	"api_keys.update",
	"asm.groups.create",
	"asm.groups.delete",
	"asm.groups.read",
	"asm.groups.suppressions.create",
	"asm.groups.suppressions.delete",
	"asm.groups.suppressions.read",
	"asm.groups.suppressions.update",
	"asm.groups.update",
	"asm.suppressions.global.create",
	"asm.suppressions.global.delete",
	"asm.suppressions.global.read",
	"asm.suppressions.global.update",
	"billing.create",
	"billing.delete",
	"billing.read",
	"billing.update",
	"browsers.stats.read",
	"categories.create",
	"categories.delete",
	"categories.read",
	"categories.stats.read",
	"categories.stats.sums.read",
	"categories.update",
	"clients.desktop.stats.read",
	"clients.phone.stats.read",
	"clients.stats.read",
	"clients.tablet.stats.read",
	"clients.webmail.stats.read",
	"credentials.create",
	"credentials.delete",
	"credentials.read",
	"credentials.update",
	"design_library.create",
	"design_library.delete",
	"design_library.read",
	"design_library.update",
	"devices.stats.read",
	"email_activity.read",
	"email_testing.read",
	"email_testing.write",
	"geo.stats.read",
	"ips.assigned.read",
	"ips.pools.create",
	"ips.pools.delete",
	"ips.pools.ips.create",
	"ips.pools.ips.delete",
	"ips.pools.ips.read",
	"ips.pools.ips.update",
	"ips.pools.read",
	"ips.pools.update",
	"ips.read",
	"ips.warmup.create",
	"ips.warmup.delete",
	"ips.warmup.read",
	"ips.warmup.update",
	"mail.batch.create",
	"mail.batch.delete",
	"mail.batch.read",
	"mail.batch.update",
	"mail.send",
	"mail_settings.address_whitelist.create",
	"mail_settings.address_whitelist.delete",
	"mail_settings.address_whitelist.read",
	"mail_settings.address_whitelist.update",
	"mail_settings.bcc.create",
	"mail_settings.bcc.delete",
	"mail_settings.bcc.read",
	"mail_settings.bcc.update",
	"mail_settings.bounce_purge.create",
	"mail_settings.bounce_purge.delete",
	"mail_settings.bounce_purge.read",
	"mail_settings.bounce_purge.update",
	"mail_settings.footer.create",
	"mail_settings.footer.delete",
	"mail_settings.footer.read",
	"mail_settings.footer.update",
	"mail_settings.forward_bounce.create",
	"mail_settings.forward_bounce.delete",
	"mail_settings.forward_bounce.read",
	"mail_settings.forward_bounce.update",
	"mail_settings.forward_spam.create",
	"mail_settings.forward_spam.delete",
	"mail_settings.forward_spam.read",
	"mail_settings.forward_spam.update",
	"mail_settings.plain_content.create",
	"mail_settings.plain_content.delete",
	"mail_settings.plain_content.read",
	"mail_settings.plain_content.update",
	"mail_settings.read",
	"mail_settings.spam_check.create",
	"mail_settings.spam_check.delete",
	"mail_settings.spam_check.read",
	"mail_settings.spam_check.update",
	"mail_settings.template.create",
	"mail_settings.template.delete",
	"mail_settings.template.read",
	"mail_settings.template.update",
	"mailbox_providers.stats.read",
	"marketing.automation.read",
	"marketing.read",
	"marketing_campaigns.create",
	"marketing_campaigns.delete",
	"marketing_campaigns.read",
	"marketing_campaigns.update",
	"messages.read",
	"newsletter.create",
	"newsletter.delete",
	"newsletter.read",
	"newsletter.update",
	"partner_settings.new_relic.create",
	"partner_settings.new_relic.delete",
	"partner_settings.new_relic.read",
	"partner_settings.new_relic.update",
	"partner_settings.read",
	"partner_settings.sendwithus.create",
	"partner_settings.sendwithus.delete",
	"partner_settings.sendwithus.read",
	"partner_settings.sendwithus.update",
	"recipients.erasejob.create",
	"recipients.erasejob.read",
	"sender_verification_eligible",
	"signup.trigger_confirmation",
	"stats.global.read",
	"stats.read",
	"subusers.create",
	"subusers.credits.create",
	"subusers.credits.delete",
	"subusers.credits.read",
	"subusers.credits.remaining.create",
	"subusers.credits.remaining.delete",
	"subusers.credits.remaining.read",
	"subusers.credits.remaining.update",
	"subusers.credits.update",
	"subusers.delete",
	"subusers.monitor.create",
	"subusers.monitor.delete",
	"subusers.monitor.read",
	"subusers.monitor.update",
	"subusers.read",
	"subusers.reputations.read",
	"subusers.stats.monthly.read",
	"subusers.stats.read",
	"subusers.stats.sums.read",
	"subusers.summary.read",
	"subusers.update",
	"suppression.blocks.create",
	"suppression.blocks.delete",
	"suppression.blocks.read",
	"suppression.blocks.update",
	"suppression.bounces.create",
	"suppression.bounces.delete",
	"suppression.bounces.read",
	"suppression.bounces.update",
	"suppression.create",
	"suppression.delete",
	"suppression.invalid_emails.create",
	"suppression.invalid_emails.delete",
	"suppression.invalid_emails.read",
	"suppression.invalid_emails.update",
	"suppression.read",
	"suppression.spam_reports.create",
	"suppression.spam_reports.delete",
	"suppression.spam_reports.read",
	"suppression.spam_reports.update",
	"suppression.unsubscribes.create",
	"suppression.unsubscribes.delete",
	"suppression.unsubscribes.read",
	"suppression.unsubscribes.update",
	"suppression.update",
	"teammates.create",
	"teammates.delete",
	"teammates.read",
	"teammates.update",
	"templates.create",
	"templates.delete",
	"templates.read",
	"templates.update",
	"templates.versions.activate.create",
	"templates.versions.activate.delete",
	"templates.versions.activate.read",
	"templates.versions.activate.update",
	"templates.versions.create",
	"templates.versions.delete",
	"templates.versions.read",
	"templates.versions.update",
	"tracking_settings.click.create",
	"tracking_settings.click.delete",
	"tracking_settings.click.read",
	"tracking_settings.click.update",
	"tracking_settings.google_analytics.create",
	"tracking_settings.google_analytics.delete",
	"tracking_settings.google_analytics.read",
	"tracking_settings.google_analytics.update",
	"tracking_settings.open.create",
	"tracking_settings.open.delete",
	"tracking_settings.open.read",
	"tracking_settings.open.update",
	"tracking_settings.read",
	"tracking_settings.subscription.create",
	"tracking_settings.subscription.delete",
	"tracking_settings.subscription.read",
	"tracking_settings.subscription.update",
	"ui.confirm_email",
	"ui.provision",
	"ui.signup_complete",
	"user.account.read",
	"user.credits.read",
	"user.email.create",
	"user.email.delete",
	"user.email.read",
	"user.email.update",
	"user.multifactor_authentication.create",
	"user.multifactor_authentication.delete",
	"user.multifactor_authentication.read",
	"user.multifactor_authentication.update",
	"user.password.read",
	"user.password.update",
	"user.profile.create",
	"user.profile.delete",
	"user.profile.read",
	"user.profile.update",
	"user.scheduled_sends.create",
	"user.scheduled_sends.delete",
	"user.scheduled_sends.read",
	"user.scheduled_sends.update",
	"user.settings.enforced_tls.read",
	"user.settings.enforced_tls.update",
	"user.timezone.create",
	"user.timezone.delete",
	"user.timezone.read",
	"user.timezone.update",
	"user.username.read",
	"user.username.update",
	"user.webhooks.event.settings.create",
	"user.webhooks.event.settings.delete",
	"user.webhooks.event.settings.read",
	"user.webhooks.event.settings.update",
	"user.webhooks.event.test.create",
	"user.webhooks.event.test.delete",
	"user.webhooks.event.test.read",
	"user.webhooks.event.test.update",
	"user.webhooks.parse.settings.create",
	"user.webhooks.parse.settings.delete",
	"user.webhooks.parse.settings.read",
	"user.webhooks.parse.settings.update",
	"user.webhooks.parse.stats.read",
	"whitelabel.create",
	"whitelabel.delete",
	"whitelabel.read",
	"whitelabel.update",
}

func ResourceSchema() map[string]*schema.Schema {
	s := DataSourceSchema()

	s["id"] = &schema.Schema{
		Description: idDesc,
		Type:        schema.TypeString,
		Computed:    true,
	}
	s["name"] = &schema.Schema{
		Description:  nameDesc,
		Type:         schema.TypeString,
		Required:     true,
		ValidateFunc: validation.StringLenBetween(1, 255),
	}
	s["description"] = &schema.Schema{
		Description:  descriptionDesc,
		Type:         schema.TypeString,
		Optional:     true,
		ValidateFunc: validation.StringLenBetween(0, 1000),
	}
	s["scopes"] = &schema.Schema{
		Description: scopesDesc,
		Type:        schema.TypeList,
		Required:    true,
		MinItems:    1,
		Elem: &schema.Schema{
			Type:         schema.TypeString,
			ValidateFunc: validation.StringInSlice(validScopes, false),
		},
	}

	return s
}

func DataSourceSchema() map[string]*schema.Schema {
	return map[string]*schema.Schema{
		"id": {
			Description: idDesc,
			Type:        schema.TypeString,
			Required:    true,
		},
		"name": {
			Description: nameDesc,
			Type:        schema.TypeString,
			Computed:    true,
		},
		"description": {
			Description: descriptionDesc,
			Type:        schema.TypeString,
			Computed:    true,
		},
		"scopes": {
			Description: scopesDesc,
			Type:        schema.TypeList,
			Computed:    true,
			Elem: &schema.Schema{
				Type: schema.TypeString,
			},
		},
		"type": {
			Description: typeDesc,
			Type:        schema.TypeString,
			Computed:    true,
		},
	}
}
