---
name: Build
on:
  push:
    branches:
      - "main"
      - "**-ci"
  pull_request:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    permissions:
      contents: read
      pull-requests: read
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4
        with:
          submodules: true
      
      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version-file: 'go.mod'
          cache: true
      
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3
        with:
          terraform_version: "1.5.0"
      
      - name: Install golangci-lint
        uses: golangci/golangci-lint-action@v7
        with:
          version: v2.2.2
          install-mode: "binary"
      
      - name: Lint
        run: make lint
      
      - name: Build
        run: make build
